Nop.Plugin.Widgets.AzPersonalizer/Controllers/AzPersonalizerController.cs
namespace Nop.Plugin.Widgets.AzPersonalizer.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Nop.Core;
    using Nop.Plugin.Widgets.AzPersonalizer.Models;
    using Nop.Services.Configuration;
    using Nop.Services.Localization;
    using Nop.Services.Media;
    using Nop.Services.Messages;
    using Nop.Services.Security;
    using Nop.Web.Framework;
    using Nop.Web.Framework.Controllers;
    using Nop.Web.Framework.Mvc.Filters;

   [AuthorizeAdmin]
   [Area(AreaNames.Admin)]
   [AutoValidateAntiforgeryToken]
    public class AzPersonalizerController : BasePluginController
    {

        #region fields

        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;

        #endregion

        #region ctor

        public AzPersonalizerController (ILocalizationService localizationService ,
            INotificationService notificationService ,
            IPermissionService permissionService ,
            ISettingService settingService ,
            IStoreContext storeContext)
        {
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _settingService = settingService;
            _storeContext = storeContext;
        }

        #endregion

        #region methods

        public async Task<IActionResult> Configure ()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageWidgets))
            {
                return AccessDeniedView();
            }

            //load settings for a chosen store scope
            int storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            AzPersonalizerSettings azPersonalizerSettings =
                await _settingService.LoadSettingAsync<AzPersonalizerSettings>(storeScope);
            ConfigurationModel model = new()
            {
                APIkey = azPersonalizerSettings.APIkey,
                Endpoint = azPersonalizerSettings.Endpoint,
                ActiveStoreScopeConfiguration = storeScope
            };

            if (storeScope > 0)
            {
                model.APIKey_OverrideForStore =
                    await _settingService.SettingExistsAsync(azPersonalizerSettings, x => x.Endpoint,
                        storeScope);
                model.Endpoint_OverrideForStore =
                    await _settingService.SettingExistsAsync(azPersonalizerSettings, x => x.APIkey, storeScope);
            }

            return View("~/Plugins/Widgets.AzPersonalizer/Views/Configure.cshtml", model);
        }

       [HttpPost]
        public async Task<IActionResult> Configure (ConfigurationModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageWidgets))
            {
                return AccessDeniedView();
            }

            //load settings for a chosen store scope
            int storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            AzPersonalizerSettings azPersonalizerSettings =
                await _settingService.LoadSettingAsync<AzPersonalizerSettings>(storeScope);


            azPersonalizerSettings.Endpoint = model?.Endpoint;
            azPersonalizerSettings.APIkey = model?.APIkey;


            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */
            await _settingService.SaveSettingOverridablePerStoreAsync(azPersonalizerSettings, x => x.Endpoint,
                model.Endpoint_OverrideForStore, storeScope);
            await _settingService.SaveSettingOverridablePerStoreAsync(azPersonalizerSettings, x => x.APIkey,
                model.APIKey_OverrideForStore, storeScope);


            //now clear settings cache
            await _settingService.ClearCacheAsync();

            //get current picture identifiers

            _notificationService.SuccessNotification(
                await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

            return await Configure();
        }

        #endregion
    }
}

Nop.Plugin.Widgets.AzPersonalizer/Views/Configure.cshtml
@model Nop.Plugin.Widgets.AzPersonalizer.Models.ConfigurationModel

@{
	Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")
<form asp-controller="AzPersonalizer" asp-action="Configure" method="post">
	<section class="content">
		<div class="container-fluid">
			<div class="cards-group">
				<div class="card card-default">
					<div class="card-header">
						Select your data:
					</div>
					<div class="card-body">
						<div class="form-group row">
							<div class="col-md-3">
								<nop-override-store-checkbox asp-for="APIKey_OverrideForStore" asp-input="APIkey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
								<nop-label asp-for="APIkey" />
							</div>
							<div class="col-md-9">
								<nop-editor asp-for="APIkey" />
								<span asp-validation-for="APIkey"></span>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-3">
								<nop-override-store-checkbox asp-for="Endpoint_OverrideForStore" asp-input="Endpoint" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
								<nop-label asp-for="Endpoint" />
							</div>
							<div class="col-md-9">
								<nop-editor asp-for="Endpoint" />
								<span asp-validation-for="Endpoint"></span>
							</div>
						</div>

					</div>
				</div>

				<div class="card card-default">
					<div class="card-body">
						<div class="form-group row">
							<div class="col-md-9 offset-md-3">
								<button type="submit" name="save" class="btn btn-primary">@T("Admin.Common.Save")</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</form>

Nop.Plugin.Widgets.AzPersonalizer/Views/Recommendations.cshtml
@using Nop.Plugin.Widgets.AzPersonalizer.Models
@model Nop.Plugin.Widgets.AzPersonalizer.Models.ProductOverviewToRankingList
<style>
	#wrapper-class {
	}
</style>

@if (Model.ProductOverviewList.Count > 0)
{
	<div class="related-products-grid product-grid">
		<div class="title">
			<strong>Recommended Products:</strong>
		</div>
		<div class="item-grid wrapper-class">
			@{
				int i = 0;

			}
			@foreach (var item in Model.ProductOverviewList)
			{
				{
					if (i > 3) break;
					int thisIteration = i++;
					<div class="item-box">
						@await Html.PartialAsync("~/Plugins/Widgets.AzPersonalizer/Views/_ProductRecommendationBox.cshtml", new ProductOverviewRecommendation(item, Model.RankingID, thisIteration))
					</div>
				}
			}
		</div>
	</div>
}

Nop.Plugin.Widgets.AzPersonalizer/Views/_ProductRecommendationBox.cshtml
@model Nop.Plugin.Widgets.AzPersonalizer.Models.ProductOverviewRecommendation
@using Nop.Core
@using Nop.Core.Domain.Catalog
@using Nop.Core.Domain.Orders
@using Nop.Core.Domain.Tax
@using Nop.Web.Extensions
@inject CatalogSettings catalogSettings
@inject IWorkContext workContext
@{
	//prepare "Add to cart" AJAX link
	var addtocartlink = "";
	var shoppingCartTypeId = (int)ShoppingCartType.ShoppingCart;
	var quantity = 1;
	var queryForRecommendation = "?azrec";
	if (Model.ProductOverviewModel.ProductPrice.ForceRedirectionAfterAddingToCart)
	{
		addtocartlink = Url.RouteUrl("AddProductToCart-Catalog", new { productId = Model.ProductOverviewModel.Id, shoppingCartTypeId = shoppingCartTypeId, quantity = quantity, forceredirection = Model.ProductOverviewModel.ProductPrice.ForceRedirectionAfterAddingToCart });
	}
	else
	{
		addtocartlink = Url.RouteUrl("AddProductToCart-Catalog", new { productId = Model.ProductOverviewModel.Id, shoppingCartTypeId = shoppingCartTypeId, quantity = quantity });
	}

	var addtowishlistlink = Url.RouteUrl("AddProductToCart-Catalog", new { productId = Model.ProductOverviewModel.Id, shoppingCartTypeId = (int)ShoppingCartType.Wishlist, quantity = quantity });
	var addtocomparelink = Url.RouteUrl("AddProductToCompare", new { productId = Model.ProductOverviewModel.Id });
}
<div class="product-item" data-productid="@Model.ProductOverviewModel.Id">
	<div class="picture">
		<a href="@(Url.RouteUrl("Product", new { SeName = Model.ProductOverviewModel.SeName }) + queryForRecommendation)" title="@Model.ProductOverviewModel.DefaultPictureModel.Title">
			<img alt="@Model.ProductOverviewModel.DefaultPictureModel.AlternateText" src="@Model.ProductOverviewModel.DefaultPictureModel.ImageUrl" title="@Model.ProductOverviewModel.DefaultPictureModel.Title" />
		</a>
	</div>
	<div class="details">
		<h2 class="product-title">
			<a href="@(Url.RouteUrl("Product", new { SeName = Model.ProductOverviewModel.SeName }) + queryForRecommendation)">@Model.ProductOverviewModel.Name</a>
		</h2>
		@if (catalogSettings.ShowSkuOnCatalogPages && !string.IsNullOrEmpty(Model.ProductOverviewModel.Sku))
		{
			<div class="sku">
				@Model.ProductOverviewModel.Sku
			</div>
		}

		<div class="description">
			@Html.Raw(Model.ProductOverviewModel.ShortDescription)
		</div>
		<div class="add-info">
			@await Component.InvokeAsync("Widget", new { widgetZone = PublicWidgetZones.ProductBoxAddinfoBefore, additionalData = Model })
			<div class="prices">
				@if (!string.IsNullOrEmpty(Model.ProductOverviewModel.ProductPrice.OldPrice))
				{
					<span class="price old-price">@Model.ProductOverviewModel.ProductPrice.OldPrice</span>
				}
				<span class="price actual-price">@Model.ProductOverviewModel.ProductPrice.Price</span>
				@if (Model.ProductOverviewModel.ProductPrice.DisplayTaxShippingInfo)
				{
					var inclTax = await workContext.GetTaxDisplayTypeAsync() == TaxDisplayType.IncludingTax;
					//tax info is already included in the price (incl/excl tax). that's why we display only shipping info here
					//of course, you can modify appropriate locales to include VAT info there
					<span class="tax-shipping-info">
						@T(inclTax ? "Products.Price.TaxShipping.InclTax" : "Products.Price.TaxShipping.ExclTax", Url.RouteUrl("Topic", new { SeName = await Html.GetTopicSeNameAsync("shippinginfo") }))
					</span>
				}
				@if (!string.IsNullOrEmpty(Model.ProductOverviewModel.ProductPrice.BasePricePAngV))
				{
					<div class="base-price-pangv">
						@Model.ProductOverviewModel.ProductPrice.BasePricePAngV
					</div>
				}
			</div>
			@await Component.InvokeAsync("Widget", new { widgetZone = PublicWidgetZones.ProductBoxAddinfoMiddle, additionalData = Model })
			<div class="buttons">
				@*<button type="button" class="button-1 product-box-detail-button" onclick="setLocation('@Url.RouteUrl("Product", new { SeName = Model.ProductOverviewModel.SeName })')">@T("Products.Details")</button>*@
				@if (!Model.ProductOverviewModel.ProductPrice.DisableBuyButton)
				{
					var addToCartText = T("ShoppingCart.AddToCart").Text;
					if (Model.ProductOverviewModel.ProductPrice.IsRental)
					{
						addToCartText = T("ShoppingCart.Rent").Text;
					}
					if (Model.ProductOverviewModel.ProductPrice.AvailableForPreOrder)
					{
						addToCartText = T("ShoppingCart.PreOrder").Text;
					}
					<button type="button" class="button-2 product-box-add-to-cart-button" onclick="AjaxCart.addproducttocart_catalog('@addtocartlink');return false;">@(addToCartText)</button>
				}
				@if (!Model.ProductOverviewModel.ProductPrice.DisableAddToCompareListButton)
				{
					<button type="button" class="button-2 add-to-compare-list-button" title="@T("ShoppingCart.AddToCompareList")" onclick="AjaxCart.addproducttocomparelist('@addtocomparelink');return false;">@T("ShoppingCart.AddToCompareList")</button>
				}
				@if (!Model.ProductOverviewModel.ProductPrice.DisableWishlistButton)
				{
					<button type="button" class="button-2 add-to-wishlist-button" title="@T("ShoppingCart.AddToWishlist")" onclick="AjaxCart.addproducttocart_catalog('@addtowishlistlink');return false;">@T("ShoppingCart.AddToWishlist")</button>
				}
			</div>
			@await Component.InvokeAsync("Widget", new { widgetZone = PublicWidgetZones.ProductBoxAddinfoAfter, additionalData = Model })
		</div>
	</div>
</div>